
version: 2

models:
  # Google OSM POI matching
  - name: google_osm_poi_matching
    description: 'Matching of OSM POIs to Google results based on name and location'
    columns:
      - name: osm_id
        description: 'Combined OSM type with respective OSM ID'
        tests:
          - unique
          - not_null
      - name: internal_id
        description: 'ID of the Google POI'
        tests:
          - not_null
      - name: confidence
        description: 'Confidence score based on name and location'
        tests:
          - not_null

  # POI
  - name: poi
    description: 'POIs with matching admin boundary'
    columns:
      - name: poi_id
        description: 'Unique ID referring to a POI'
        tests:
          - unique
          - not_null
      - name: external_poi_id
        description: 'Custom defined POI ID'
        tests:
          - unique
      - name: poi_confidence_google
        description: 'The confidence of the Google result based on the query input'
      - name: poi_google_place_id
        description: "Google's ID for entries on Google Maps"
      - name: poi_h3_index
        description: 'H3 index of the POI'
        tests:
          - not_null
      - name: latitude
        description: 'Latitude of the center of the H3 index'
        tests:
          - not_null
      - name: longitude
        description: 'Longitude of the center of the H3 index'
        tests:
          - not_null
      - name: poi_name_google
        description: 'Name of the POI how it appears on Google'
      - name: poi_name_osm
        description: 'Name of the POI how it appears on OSM'
      - name: poi_categories_osm
        description: 'POI categories based on OSM'
      - name: poi_categories_google
        description: 'POI categories based on Google Maps'
      - name: poi_categories_google_raw
        description: 'Raw category tags returned from Google Maps that are used to build high-level POI categories'
      - name: poi_address_osm
        description: 'The address string based on OSM address tags'
      - name: poi_address_google
        description: 'The address string form Google Maps'
      - name: poi_reviews
        description: 'Number of reviews on Google Maps'
      - name: poi_rating
        description: 'Average rating on Google Maps'
      - name: poi_price_level
        description: 'Price level on Google Maps'
      - name: poi_opening_time_total
        description: 'The total opening hours of the POI during a given timeframe'
      - name: poi_popularity_total
        description: 'The total popularity values of the POI during a given timeframe'
      - name: poi_popularity_morning_total
        description: 'The total popularity values of the POI in the morning hours during a given timeframe'
      - name: poi_popularity_noon_total
        description: 'The total popularity values of the POI in the noon hours during a given timeframe'
      - name: poi_popularity_afternoon_total
        description: 'The total popularity values of the POI in the afternoon hours during a given timeframe'
      - name: poi_popularity_evening_total
        description: 'The total popularity values of the POI in the evening hours during a given timeframe'
      - name: poi_closed
        description: 'Indicating whether the POI is marked as closed on Google Maps (temporarily or permanently)'
      - name: poi_closed_permanently
        description: 'Indicating whether the POI is marked as permanently closed on Google Maps'
      - name: poi_spending_time
        description: 'The average duration people spend at the POI in minutes'
      - name: poi_waiting_time
        description: 'The average duration people wait at the POI in minutes cumulated throughout one week'
      - name: poi_inside_of
        description: 'Indicating whether the POI is located inside another POI (e.g., a shopping mall)'
      - name: h3_resolution
        description: 'The resolution of the H3 index (for POI 15)'
        tests:
          - not_null
          - accepted_values:
              values: [ 15 ]
      - name: poi_address_city
        description: 'Name of the city containing POI coordinates based on matched GeoNames and OSM data'
      - name: poi_address_country
        description: 'Name of admin boundary having kuwala_admin_level 1 containing POI coordinates'

  # POI city based on admin boundary
  - name: poi_address_city
    description: 'City containing POI coordinates based on matched GeoNames and OSM data'
    columns:
      - name: poi_id
        description: 'Unique ID referring to a POI'
        tests:
          - unique
          - not_null
      - name: city_name
        description: 'Name of matching city'
        tests:
          - not_null

  # POI country based on admin boundary
  - name: poi_address_country
    description: 'Admin boundary name with lowest admin level containing POI coordinates'
    columns:
      - name: poi_id
        description: 'Unique ID referring to a POI'
        tests:
          - unique
          - not_null
      - name: name
        description: 'Name of matching admin boundary'
        tests:
          - not_null
      - name: id
        description: 'ID of matching admin boundary'
        tests:
          - not_null

  # POI data aggregated on H3 indexes
  - name: poi_aggregated
    description: 'Aggregated POI data based on H3 resolution'
    columns:
      - name: h3_index
        description: 'H3 index data has been aggregated on'
        tests:
          - unique
          - not_null
      - name: pois_total
        description: 'Total number of POIs in H3 index'
        tests:
          - not_null
      - name: poi_confidence_google_average
        description: 'The average confidence of POIs with Google data'
      - name: poi_reviews_total
        description: 'The total amount of reviews across all POIs'
      - name: poi_rating_average
        description: 'The average rating across all POIs'
      - name: poi_price_level_average
        description: 'The average price level across all POIs'
      - name: poi_opening_time_total
        description: 'The total opening time throughout an entire week across all POIs'
      - name: poi_popularity_total
        description: 'The total popularity scores throughout an entire week across all POIs'
      - name: poi_popularity_morning_total
        description: 'The total popularity values of the POI in the morning hours during one week across all POIs'
      - name: poi_popularity_noon_total
        description: 'The total popularity values of the POI in the noon hours during one week across all POIs'
      - name: poi_popularity_afternoon_total
        description: 'The total popularity values of the POI in the afternoon hours during one week across all POIs'
      - name: poi_popularity_evening_total
        description: 'The total popularity values of the POI in the evening hours during one week across all POIs'
      - name: poi_closed_total
        description: 'Total number of POIs marked as closed'
      - name: poi_closed_permanently_total
        description: 'Total number of POIs marked as permanently closed'
      - name: poi_spending_time_average
        description: 'The average spending time across all POIs'
      - name: poi_waiting_time_average
        description: 'The average waiting time cumulated throughout one week across all POIs'
      - name: poi_inside_of_total
        description: 'Number of POIs that are located inside another POI'
      - name: number_of_espresso_houses
        description: 'Number of Espresso Houses within the given H3 index'
      - name: number_of_competitors
        description: 'Number of competitors within the given H3 index'
      - name: poi_category_administration
        description: 'Number of POIs belonging to the POI category "administration"'
      - name: poi_category_airport
        description: 'Number of POIs belonging to the POI category "airport"'
      - name: poi_category_apartment
        description: 'Number of POIs belonging to the POI category "apartment"'
      - name: poi_category_art_culture
        description: 'Number of POIs belonging to the POI category "art_culture"'
      - name: poi_category_automobile
        description: 'Number of POIs belonging to the POI category "automobile"'
      - name: poi_category_beauty
        description: 'Number of POIs belonging to the POI category "beauty"'
      - name: poi_category_cafe
        description: 'Number of POIs belonging to the POI category "cafe"'
      - name: poi_category_drinks
        description: 'Number of POIs belonging to the POI category "drinks"'
      - name: poi_category_education
        description: 'Number of POIs belonging to the POI category "education"'
      - name: poi_category_entertainment
        description: 'Number of POIs belonging to the POI category "entertainment"'
      - name: poi_category_food
        description: 'Number of POIs belonging to the POI category "food"'
      - name: poi_category_groceries
        description: 'Number of POIs belonging to the POI category "groceries"'
      - name: poi_category_medical
        description: 'Number of POIs belonging to the POI category "medical"'
      - name: poi_category_misc
        description: 'Number of POIs belonging to the POI category "misc"'
      - name: poi_category_office
        description: 'Number of POIs belonging to the POI category "office"'
      - name: poi_category_public_service
        description: 'Number of POIs belonging to the POI category "public_service"'
      - name: poi_category_public_transportation
        description: 'Number of POIs belonging to the POI category "public_transportation"'
      - name: poi_category_recreation
        description: 'Number of POIs belonging to the POI category "recreation"'
      - name: poi_category_religious_building
        description: 'Number of POIs belonging to the POI category "religious_building"'
      - name: poi_category_service
        description: 'Number of POIs belonging to the POI category "service"'
      - name: poi_category_shopping
        description: 'Number of POIs belonging to the POI category "shopping"'
      - name: poi_category_social_service
        description: 'Number of POIs belonging to the POI category "social_service"'
      - name: poi_category_shopping
        description: 'Number of POIs belonging to the POI category "shopping"'
      - name: poi_category_social_service
        description: 'Number of POIs belonging to the POI category "social_service"'
      - name: poi_category_sport
        description: 'Number of POIs belonging to the POI category "sport"'
      - name: poi_category_tourism
        description: 'Number of POIs belonging to the POI category "tourism"'
      - name: poi_category_wholesaler
        description: 'Number of POIs belonging to the POI category "wholesaler"'
      - name: latitude
        description: 'Latitude of the center of the H3 index'
        tests:
          - not_null
          - unique
      - name: longitude
        description: 'Longitude of the center of the H3 index'
        tests:
          - not_null
          - unique
      - name: geo_boundary
        description: 'GeoJSON of the H3 index'
        tests:
          - not_null
          - unique
      - name: resolution
        description: 'Resolution of the H3 index'
        tests:
          - not_null

  # POI matched
  - name: poi_matched
    description: 'POI model based on OSM and Google data'
    columns:
      - name: poi_id
        description: 'Unique ID referring to a POI'
        tests:
          - unique
          - not_null
      - name: external_poi_id
        description: 'Custom defined POI ID'
        tests:
          - unique
      - name: poi_confidence_google
        description: 'The confidence of the Google result based on the query input'
      - name: poi_google_place_id
        description: "Google's ID for entries on Google Maps"
      - name: poi_h3_index
        description: 'H3 index of the POI'
        tests:
          - not_null
      - name: latitude
        description: 'Latitude of the center of the H3 index'
        tests:
          - not_null
      - name: longitude
        description: 'Longitude of the center of the H3 index'
        tests:
          - not_null
      - name: poi_name_google
        description: 'Name of the POI how it appears on Google'
      - name: poi_name_osm
        description: 'Name of the POI how it appears on OSM'
      - name: poi_categories_osm
        description: 'POI categories based on OSM'
      - name: poi_categories_google
        description: 'POI categories based on Google Maps'
      - name: poi_categories_google_raw
        description: 'Raw category tags returned from Google Maps that are used to build high-level POI categories'
      - name: poi_address_osm
        description: 'The address string based on OSM address tags'
      - name: poi_address_google
        description: 'The address string form Google Maps'
      - name: poi_reviews
        description: 'Number of reviews on Google Maps'
      - name: poi_rating
        description: 'Average rating on Google Maps'
      - name: poi_price_level
        description: 'Price level on Google Maps'
      - name: poi_opening_time_total
        description: 'The total opening hours of the POI during a given timeframe'
      - name: poi_popularity_total
        description: 'The total popularity values of the POI during a given timeframe'
      - name: poi_popularity_morning_total
        description: 'The total popularity values of the POI in the morning hours during a given timeframe'
      - name: poi_popularity_noon_total
        description: 'The total popularity values of the POI in the noon hours during a given timeframe'
      - name: poi_popularity_afternoon_total
        description: 'The total popularity values of the POI in the afternoon hours during a given timeframe'
      - name: poi_popularity_evening_total
        description: 'The total popularity values of the POI in the evening hours during a given timeframe'
      - name: poi_closed
        description: 'Indicating whether the POI is marked as closed on Google Maps (temporarily or permanently)'
      - name: poi_closed_permanently
        description: 'Indicating whether the POI is marked as permanently closed on Google Maps'
      - name: poi_spending_time
        description: 'The average duration people spend at the POI in minutes'
      - name: poi_waiting_time
        description: 'The average duration people wait at the POI in minutes cumulated throughout one week'
      - name: poi_inside_of
        description: 'Indicating whether the POI is located inside another POI (e.g., a shopping mall)'
      - name: h3_resolution
        description: 'The resolution of the H3 index (for POI 15)'
        tests:
          - not_null
          - accepted_values:
              values: [ 15 ]

  # POI popularity data as a time series
  - name: poi_popularity_time_series
    description: 'The hourly popularity of a POI as a time series'
    columns:
      - name: poi_id
        description: 'Unique ID referring to a POI'
        tests:
          - not_null
      - name: popularity
        description: 'Popularity score between 0 and 100 indicating relative to the POI how busy it is at the given hour'
        tests:
          - not_null
      - name: timestamp
        description: 'ISO date time string for the hour the popularity value is referring to'
        tests:
          - not_null